import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const apercu = localFont({
  src: [
    { path: "../public/fonts/Apercu-Light.woff2", weight: "300", style: "normal" },
    { path: "../public/fonts/Apercu-Regular.woff2", weight: "400", style: "normal" },
    { path: "../public/fonts/Apercu-Medium.woff2", weight: "500", style: "normal" },
    { path: "../public/fonts/Apercu-Bold.woff2", weight: "700", style: "normal" },
  ],
  display: "swap",
  variable: "--font-apercu",
});

export const metadata: Metadata = {
  title: "UPF Rankings Simulator",
  description: "Generated by EWE18 UPF Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${apercu.className} h-full antialiased`}>
      <body className="min-h-full bg-white min-w-full h-full w-full">{children}</body>
    </html>
  );
}
